[package]
name = "lintls"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
nix = { version = "0.29.0", features = ["process"] }
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
simple-logging = "2.0.2"
sysinfo = "0.31.4"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
tower-lsp = "0.20.0"
