[package]
name = "pickls"
version = "0.2.0"
edition = "2021"
license = "MIT"
keywords = ["LSP", "protocol", "command-line", "ide", "diagnostics"]
categories = ["development-tools", "text-editors"]
description = "The General Purpose Language Server for Command-Line Linters and Formatters"
readme = "README.md"
homepage = "https://github.com/wbbradley/pickls"
repository = "https://github.com/wbbradley/pickls"

[dependencies]
futures = "0.3.31"
libc = "0.2.159"
log = "0.4.22"
nix = { version = "0.29.0", features = ["process"] }
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
simple-logging = "2.0.2"
sysinfo = "0.31.4"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
tower-lsp = "0.20.0"
