[[tools]]
match_extensions = [ ".toml" ]
program = "tomllint"
pattern = "^([^:]+):(\\d+):(\\d+):([^:]+):(.*)$"
filename_match = 1
line_match = 2
description_match = 5

[[tools]]
match_extensions = [ ".c", ".h" ]
program = "cc"
pattern = "^([^:]+):(\\d+):(\\d+):([^:]+):(.*)$"
filename_match = 1
line_match = 2
description_match = 5

[[tools]]
match_extensions = [ ".py" ]
program = "mypy"
pattern = "^([^:]+):(\\d+): error: (.*$"
filename_match = 1
line_match = 2
description_match = 3
